name: Build Flutter APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Find pubspec.yaml and Build APK
        run: |
          PUBSPEC_PATH=$(find . -name "pubspec.yaml" -not -path "*/.*" | head -n 1)
          if [ -z "$PUBSPEC_PATH" ]; then
            echo "Error: pubspec.yaml not found in repository!"
            exit 1
          fi
          PROJECT_DIR=$(dirname "$PUBSPEC_PATH")
          echo "Found project directory: $PROJECT_DIR"
          cd "$PROJECT_DIR"
          flutter pub get
          flutter build apk --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: '**/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk'
